import { type Parameter } from "../commons/types";

// 1. 시장별 섹터 데이터 (방대한 양)
export const MARKET_SECTORS: Record<string, string[]> = {
    KOSPI: [
        "반도체",
        "2차전지",
        "자동차",
        "바이오/제약",
        "인터넷/플랫폼",
        "게임",
        "조선/해운",
        "방산",
        "원자력",
        "철강",
        "화학/정유",
        "건설",
        "금융/은행",
        "지주사",
        "식음료",
        "유통",
        "통신",
        "엔터테인먼트",
        "화장품",
        "항공/우주",
    ],
    KOSDAQ: [
        "AI/로봇",
        "메타버스",
        "NFT/블록체인",
        "2차전지 소재",
        "반도체 소부장",
        "진단키트",
        "신약개발",
        "의료기기",
        "웹툰/컨텐츠",
        "엔터/음원",
        "5G/통신장비",
        "자율주행",
        "스마트팩토리",
        "비료/사료",
        "교육",
        "보안",
    ],
    NASDAQ: [
        "Big Tech (MAGA)",
        "Semiconductor",
        "Cloud/SaaS",
        "Cybersecurity",
        "AI & BigData",
        "E-commerce",
        "Fintech",
        "EV (Electric Vehicle)",
        "Biotech",
        "Healthcare",
        "Gaming",
        "Social Media",
        "Clean Energy",
        "Streaming",
        "Metaverse",
        "Space",
        "Robotics",
        "3D Printing",
    ],
    Crypto: [
        "Layer 1",
        "Layer 2",
        "DeFi",
        "NFT",
        "Metaverse",
        "GameFi",
        "Meme Coin",
        "Stablecoin",
        "Oracle",
        "DEX",
        "Privacy",
        "Web3",
        "Storage",
        "Infrastructure",
        "DAO",
        "Lending",
        "Bridge",
    ],
};

// 2. 파라미터 라이브러리 (카테고리별 분류)
export const PARAMETER_LIBRARY: Parameter[] = [
    // --- Trend (추세) ---
    {
        id: "ma_5",
        category: "Trend",
        label: "5일 이평선",
        value: 5,
        unit: "일",
        description: "단기 추세선",
    },
    {
        id: "ma_20",
        category: "Trend",
        label: "20일 이평선",
        value: 20,
        unit: "일",
        description: "생명선 (중기)",
    },
    {
        id: "ma_60",
        category: "Trend",
        label: "60일 이평선",
        value: 60,
        unit: "일",
        description: "수급선 (장기)",
    },
    {
        id: "ma_120",
        category: "Trend",
        label: "120일 이평선",
        value: 120,
        unit: "일",
        description: "경기선",
    },
    {
        id: "macd_fast",
        category: "Trend",
        label: "MACD Fast",
        value: 12,
        unit: "일",
        description: "MACD 단기 지수",
    },
    {
        id: "macd_slow",
        category: "Trend",
        label: "MACD Slow",
        value: 26,
        unit: "일",
        description: "MACD 장기 지수",
    },
    {
        id: "cci",
        category: "Trend",
        label: "CCI",
        value: 14,
        unit: "일",
        description: "상품 채널 지수",
    },
    {
        id: "adx",
        category: "Trend",
        label: "ADX",
        value: 14,
        unit: "일",
        description: "추세 강도 지표",
    },

    // --- Oscillator (반전) ---
    {
        id: "rsi",
        category: "Oscillator",
        label: "RSI 기간",
        value: 14,
        unit: "일",
        description: "상대강도지수",
    },
    {
        id: "rsi_buy",
        category: "Oscillator",
        label: "RSI 매수선",
        value: 30,
        unit: "이하",
        description: "과매도 기준",
    },
    {
        id: "rsi_sell",
        category: "Oscillator",
        label: "RSI 매도선",
        value: 70,
        unit: "이상",
        description: "과매수 기준",
    },
    {
        id: "stoch_k",
        category: "Oscillator",
        label: "Stoch %K",
        value: 14,
        unit: "일",
        description: "스토캐스틱 K",
    },
    {
        id: "stoch_d",
        category: "Oscillator",
        label: "Stoch %D",
        value: 3,
        unit: "일",
        description: "스토캐스틱 D",
    },
    {
        id: "williams",
        category: "Oscillator",
        label: "Williams %R",
        value: 14,
        unit: "일",
        description: "과매수/과매도",
    },

    // --- Volatility (변동성) ---
    {
        id: "bb_len",
        category: "Volatility",
        label: "볼린저 기간",
        value: 20,
        unit: "일",
        description: "밴드 기준선",
    },
    {
        id: "bb_mult",
        category: "Volatility",
        label: "볼린저 승수",
        value: 2,
        unit: "배",
        description: "밴드 너비",
    },
    {
        id: "atr",
        category: "Volatility",
        label: "ATR",
        value: 14,
        unit: "일",
        description: "평균 진폭 범위",
    },
    {
        id: "keltner",
        category: "Volatility",
        label: "켈트너 채널",
        value: 20,
        unit: "일",
        description: "ATR 기반 채널",
    },

    // --- Volume (거래량) ---
    {
        id: "obv",
        category: "Volume",
        label: "OBV",
        value: 0,
        unit: "",
        description: "거래량 누적",
    },
    {
        id: "mfi",
        category: "Volume",
        label: "MFI",
        value: 14,
        unit: "일",
        description: "자금 흐름 지수",
    },
    {
        id: "volume_ratio",
        category: "Volume",
        label: "거래량 비율",
        value: 200,
        unit: "%",
        description: "전일 대비 급증",
    },

    // --- Risk (자금 관리) ---
    {
        id: "sl",
        category: "Risk",
        label: "손절 (SL)",
        value: 3,
        unit: "%",
        description: "Stop Loss",
    },
    {
        id: "tp",
        category: "Risk",
        label: "익절 (TP)",
        value: 5,
        unit: "%",
        description: "Take Profit",
    },
    {
        id: "trailing",
        category: "Risk",
        label: "트레일링 스탑",
        value: 2,
        unit: "%",
        description: "고점 대비 하락",
    },
    {
        id: "max_alloc",
        category: "Risk",
        label: "비중 제한",
        value: 20,
        unit: "%",
        description: "종목당 최대 비중",
    },
];
